name: IaC EKS - Local Validation Checks

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**' 

env:
  TF_VAR_aws_region: eu-central-1

jobs:
  terraform_local_checks:
    name: 'Terraform Local Checks for ${{ matrix.environment_name }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - environment_name: "dev"
            tf_dir: "environments/dev"
          - environment_name: "test"
            tf_dir: "environments/test"
          - environment_name: "prod"
            tf_dir: "environments/prod"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.x 

      - name: Install TFLint
        run: |
          TFLINT_VERSION=$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep "tag_name" | cut -d : -f 2 | tr -d " \",v")
          echo "Installing TFLint version $TFLINT_VERSION"
          curl -sL "https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/tflint
          tflint --version
        shell: bash

      - name: Terraform Init (Local Backend)
        id: init
        run: |
          cd ${{ matrix.tf_dir }}
          terraform init # No backend-config flags needed for local backend
        shell: bash

      - name: Terraform Format Check
        run: |
          cd ${{ matrix.tf_dir }}
          terraform fmt --check
        shell: bash

      - name: Terraform Validate
        run: |
          cd ${{ matrix.tf_dir }}
          terraform validate
        shell: bash

      - name: Run TFLint
        run: |
          cd ${{ matrix.tf_dir }}
          tflint --recursive # Lint all code within the environment directory
        shell: bash
        continue-on-error: true 
